language: python

python:
  - "2.7"

before_install:
  - python  $TRAVIS_BUILD_DIR/.openshift/action_hooks/gen_key.py

install: "pip install -e ."

script:
  - python $TRAVIS_BUILD_DIR/lister/manage.py test $TRAVIS_BUILD_DIR/lister/
