# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='users',
        ),
    ]
