# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20160503_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='lister',
            name='sortable',
            field=models.BooleanField(default=False),
        ),
    ]
