# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_lister_sortable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sessions',
            field=models.ManyToManyField(to='lists.Session'),
        ),
    ]
