# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20160518_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sessions',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
